### ISSUE TITLE
Reading of EEAAQeRep.v2 data crashes pyaerocom when a file is incomplete

### ISSUE THREAD

**Issue by jgriesfeller** [metno/pyaerocom#405]
as found in issue #404  the reader crashes when a file stops in the middle of a line with data (coming from an incomplete download)
by adding another exception after https://github.com/metno/pyaerocom/blob/b9b8ec397cdf956eed995d6d361486992e54350b/pyaerocom/io/read_eea_aqerep_base.py#L303-L304 this can be easily avoided

**Comment by hansbrenna** [comment]
It crashed again, so there are more files that have the same problem.

**Comment by jgriesfeller** [comment]
While testing I found another error:
this exception is wrong since it's allowed for countries not to provide data for every variable we might want to read:
https://github.com/metno/pyaerocom/blob/6612ec6ced010eeba63e96136796c262b397d299/pyaerocom/io/read_eea_aqerep_base.py#L456-L461

It's also annoying when testing locally since the EEA dataset is quite big

**Comment by jgriesfeller** [comment]
should be fixed in #408

**Comment by jgriesfeller** [comment]
closing issue due to merged PR

**Comment by hansbrenna** [comment]
@jgriesfeller this still does not seem to work. When using main-dev I stille get the same problem

**Comment by jgriesfeller** [comment]
It seems that there are files that don't even have a correct header (meaning that even the 1st line is broken). Preparing a patch and do proper testing this time...

**Comment by jgriesfeller** [comment]
@hansbrenna I have merged some more robust reading code to main-dev. Please check and report errors.
Please close the issue in case the reading works for you now.

**Comment by jgliss** [comment]
@jgriesfeller, seems like there are still some issues with the EEA reading, @dulte is looking into it to try and fix and will create a small PR for it.

**Comment by jgriesfeller** [comment]
Very weird since the file found looks fine and I thought I went through the whole data set while testing. Investigating...

**Comment by jgriesfeller** [comment]
it turnerd out that the file is actually UTF-16 encoded:
```
/lustre/storeA/project/aerocom/aerocom1/AEROCOM_OBSDATA/EEA_AQeRep.v2/renamed/SE/SE_6001_31058_2018_timeseries.csv: Little-endian UTF-16 Unicode text, with CRLF line terminators```

Making sure that these files are skipped for now

**Comment by jgriesfeller** [comment]
closing this since it seems to work now.
